program SGD;

uses
  Vcl.Forms,
  MidasLib,
  U_FrmPrincipal in 'FRM\U_FrmPrincipal.pas' {FrmPrincipal},
  U_DtmConexao in 'DTM\U_DtmConexao.pas' {DtmConexao: TDataModule},
  U_DtmPadrao in 'DTM\U_DtmPadrao.pas' {DtmPadrao: TDataModule},
  U_BibliotecaFuncoes in 'UNIT\U_BibliotecaFuncoes.pas',
  U_FrmLogin in 'FRM\U_FrmLogin.pas' {FrmLogin},
  U_FrmPadrao in 'FRM\U_FrmPadrao.pas' {FrmPadrao},
  U_TUsuario in 'CLASSES\U_TUsuario.pas',
  U_DtmDadosUsuario in 'DTM\U_DtmDadosUsuario.pas' {DtmDadosUsuario: TDataModule},
  U_FrmCadastroUsuario in 'FRM\U_FrmCadastroUsuario.pas' {FrmCadastroUsuario},
  U_TCombustivel in 'CLASSES\U_TCombustivel.pas',
  U_TTipo in 'CLASSES\U_TTipo.pas',
  U_TCategoria in 'CLASSES\U_TCategoria.pas',
  U_TMarcaModelo in 'CLASSES\U_TMarcaModelo.pas',
  U_TCor in 'CLASSES\U_TCor.pas',
  U_TTipoServico in 'CLASSES\U_TTipoServico.pas',
  U_FrmCadastroPadrao in 'FRM\U_FrmCadastroPadrao.pas' {FrmCadastroPadrao},
  U_FrmCadastroCombustivel in 'FRM\U_FrmCadastroCombustivel.pas' {FrmCadastroCombustivel},
  U_DtmDadosCombustivel in 'DTM\U_DtmDadosCombustivel.pas' {DtmDadosCombustivel: TDataModule},
  U_FrmCadastroTipo in 'FRM\U_FrmCadastroTipo.pas' {FrmCadastroTipo},
  U_DtmDadosTipo in 'DTM\U_DtmDadosTipo.pas' {DtmDadosTipo: TDataModule},
  U_DtmDadosCategoria in 'DTM\U_DtmDadosCategoria.pas' {DtmDadosCategoria: TDataModule},
  U_FrmCadastroCategoria in 'FRM\U_FrmCadastroCategoria.pas' {FrmCadastroCategoria},
  U_DtmDadosMarcaModelo in 'DTM\U_DtmDadosMarcaModelo.pas' {DtmDadosMarcaModelo: TDataModule},
  U_FrmCadastroMarcaModelo in 'FRM\U_FrmCadastroMarcaModelo.pas' {FrmCadastroMarcaModelo},
  U_DtmDadosCor in 'DTM\U_DtmDadosCor.pas' {DtmDadosCor: TDataModule},
  U_FrmCadastroCor in 'FRM\U_FrmCadastroCor.pas' {FrmCadastroCor},
  U_DtmDadosTipoServico in 'DTM\U_DtmDadosTipoServico.pas' {DtmDadosTipoServico: TDataModule},
  U_FrmCadastroTipoServico in 'FRM\U_FrmCadastroTipoServico.pas' {FrmCadastroTipoServico},
  U_TVeiculo in 'CLASSES\U_TVeiculo.pas',
  U_DtmDadosVeiculo in 'DTM\U_DtmDadosVeiculo.pas' {DtmDadosVeiculo: TDataModule},
  U_FrmCadastroVeiculo in 'FRM\U_FrmCadastroVeiculo.pas' {FrmCadastroVeiculo},
  U_TCodDesc in 'CLASSES\U_TCodDesc.pas',
  U_TServico in 'CLASSES\U_TServico.pas',
  U_DtmDadosServico in 'DTM\U_DtmDadosServico.pas' {DtmDadosServico: TDataModule},
  U_FrmCadastroCliente in 'FRM\U_FrmCadastroCliente.pas' {FrmCadastroCliente},
  U_TEndereco in 'CLASSES\U_TEndereco.pas',
  U_DtmDadosCliente in 'DTM\U_DtmDadosCliente.pas' {DtmDadosCliente: TDataModule},
  U_TCliente in 'CLASSES\U_TCliente.pas' {DtmDadosCliente: TDataModule},
  U_FrmCadastroServico in 'FRM\U_FrmCadastroServico.pas' {FrmCadastroServico},
  U_FrmSelecaoPadrao in 'FRM\U_FrmSelecaoPadrao.pas' {FrmSelecaoPadrao},
  U_FrmNegativaDeFurto in 'REL\U_FrmNegativaDeFurto.pas' {FrmNegativaDeFurto},
  U_FrmRelNegativaDeFurto in 'REL\U_FrmRelNegativaDeFurto.pas' {FrmRelNegativaDeFurto},
  U_DtmDadosRelatorioNegativaFurto in 'DTM\U_DtmDadosRelatorioNegativaFurto.pas' {DtmDadosRelatorioNegativaFurto: TDataModule},
  U_DtmDadosEmpresa in 'DTM\U_DtmDadosEmpresa.pas' {DtmDadosEmpresa: TDataModule},
  U_FrmCadastroEmpresa in 'FRM\U_FrmCadastroEmpresa.pas' {FrmCadastroEmpresa},
  U_TSituacao in 'CLASSES\U_TSituacao.pas',
  U_DtmDadosSituacao in 'DTM\U_DtmDadosSituacao.pas' {DtmDadosSituacao: TDataModule},
  U_FrmCadastroSituacao in 'FRM\U_FrmCadastroSituacao.pas' {FrmCadastroSituacao},
  U_TProcesso in 'CLASSES\U_TProcesso.pas',
  U_DtmDadosProcesso in 'DTM\U_DtmDadosProcesso.pas' {DtmDadosProcesso: TDataModule},
  U_FrmCadastroProcesso in 'FRM\U_FrmCadastroProcesso.pas' {FrmCadastroProcesso},
  U_FrmHistoricoProcesso in 'FRM\U_FrmHistoricoProcesso.pas' {FrmHistoricoProcesso},
  U_DtmDadosHistoricoProcesso in 'DTM\U_DtmDadosHistoricoProcesso.pas' {DtmDadosHistoricoProcesso: TDataModule},
  U_TEmpresa in 'CLASSES\U_TEmpresa.pas',
  U_FrmRelPadrao in 'REL\U_FrmRelPadrao.pas' {FrmRelPadrao},
  U_FrmGeraConvocacao in 'FRM\U_FrmGeraConvocacao.pas' {FrmGeraConvocacao},
  U_FrmRelConvocacao in 'REL\U_FrmRelConvocacao.pas' {FrmRelConvocacao},
  U_DtmDadosConvocacao in 'DTM\U_DtmDadosConvocacao.pas' {DtmDadosConvocacao: TDataModule},
  U_FrmRecebimentoCSV in 'FRM\U_FrmRecebimentoCSV.pas' {FrmRecebimentoCSV},
  U_FrmRelRecebimentoCSV in 'REL\U_FrmRelRecebimentoCSV.pas' {FrmRelRecebimentoCSV},
  U_DtmDadosRelRecebimentoCSV in 'DTM\U_DtmDadosRelRecebimentoCSV.pas' {DtmDadosRelRecebimentoCSV: TDataModule},
  U_FrmCadastroSeguradora in 'FRM\U_FrmCadastroSeguradora.pas' {FrmCadastroSeguradora},
  U_TSeguradora in 'CLASSES\U_TSeguradora.pas',
  U_DtmDadosSeguradora in 'DTM\U_DtmDadosSeguradora.pas' {DtmDadosSeguradora: TDataModule},
  Vcl.Themes,
  Vcl.Styles,
  U_TComprador in 'CLASSES\U_TComprador.pas',
  U_TTipoCliente in 'CLASSES\U_TTipoCliente.pas';

{$R *.res}

begin
  Application.Initialize;
  Application.MainFormOnTaskbar := True;
  Application.Title := 'SGD - Sistema de Gestão de Despachante';
  Application.CreateForm(TDtmConexao, DtmConexao);
  Application.Run;

end.
